name: "cangulo.nuke.releasecreator"
description: "Execute cangulo.nuke.releasecreator to $GITHUB_WORKSPACE path"
inputs:
  releaseSettingsPath:
    description: "release settings path. Please check the documentation for examples."
    required: true
  token:
    description: "Please provide here your personal access token or the default github token."
    required: true
  onlyCalculateReleaseNumber:
    description: "true or false"
    required: true

runs:
  using: "composite"
  steps:
    - id: calculate-release-number
      name: Calculate Release Number
      env:
        githubToken: ${{ inputs.token }}
        ReleaseSettingsPath: ${{ inputs.releaseSettingsPath }}
        PullRequestNumber: ${{ github.event.number }}
      run: |
        if [[ "${{ inputs.onlyCalculateReleaseNumber}}" == "true" ]]; then
          echo "Calculating next release number"
          ${{ github.action_path }}/app/cangulo.nuke.releasecreator CalculateNextReleaseNumber --root .
        fi 
      shell: bash
    - id: create-release
      name: Releasing
      env:
        GithubToken: ${{ inputs.token }}
        ReleaseSettingsPath: ${{ inputs.releaseSettingsPath }}
        PullRequestNumber: ${{ github.event.number }}
      run: |
        if [[ -z "${{ inputs.onlyCalculateReleaseNumber}}" || "${{ inputs.onlyCalculateReleaseNumber}}" == "false" ]]; then
          echo "Creating Release"
          ${{ github.action_path }}/app/cangulo.nuke.releasecreator CreateRelease --root .
        fi 
      shell: bash
