name: "cangulo.nuke.releasecreator"
description: "Create a GH release, create a changelog, update version in csproj files"
branding:
  icon: book-open
  color: orange
inputs:
  releaseSettingsPath:
    description: "settings to the json file with the release settings"
    required: true
  token:
    description: "Please provide here a token for pushing the changes and creating a release."
    required: true
  onlyCalculateReleaseNumber:
    description: "true or false"
    required: true

runs:
  using: "composite"
  steps:
    - id: calculate-release-number
      name: Calculate Release Number
      env:
        githubToken: ${{ inputs.token }}
        ReleaseSettingsPath: ${{ inputs.releaseSettingsPath }}
        PullRequestNumber: ${{ github.event.number }}
      run: |
        if [[ "${{ inputs.onlyCalculateReleaseNumber}}" == "true" ]]; then
          ${{ github.action_path }}/app/cangulo.nuke.releasecreator CalculateNextReleaseNumber --root .
        fi 
      shell: bash
    - id: create-release
      name: Releasing
      env:
        GithubToken: ${{ inputs.token }}
        ReleaseSettingsPath: ${{ inputs.releaseSettingsPath }}
        PullRequestNumber: ${{ github.event.number }}
      run: |
        if [[ -z "${{ inputs.onlyCalculateReleaseNumber}}" || "${{ inputs.onlyCalculateReleaseNumber}}" == "false" ]]; then
          ${{ github.action_path }}/app/cangulo.nuke.releasecreator CreateRelease --root .
        fi 
      shell: bash