name: "cangulo.nuke.releasecreator"
description: "Execute cangulo.nuke.releasecreator to $GITHUB_WORKSPACE path"
inputs:
  releaseSettingsPath:
    description: "settings to the json file with the release settings"
    required: true

runs:
  using: "composite"
  steps:
    - id: create-release
      name: Releasing
      env:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        ReleaseSettingsPath: ${{ inputs.releaseSettingsPath }}
        PullRequestNumber: ${{ github.event.number }}
      run: ${{ github.action_path }}/app/cangulo.nuke.releasecreator CreateRelease --root .
      shell: bash
