name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test-gh-action-directly:
    name: Testing Release Candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: cangulo-actions/cangulo.nuke.releasecreator@release/v0.0.1
        with:
          releaseSettingsPath: ./cicd/releaseSettings.json
          token: ${{ secrets.GITHUB_TOKEN }}