name: Release New Version

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  release-new-version:
    name: Releasing new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CREATE_PR }}
      - name: Creaing Release
        uses: cangulo-actions/cangulo.nuke.releasecreator@main
        with:
          releaseSettingsPath: ./cicd/releaseSettings.json
          token: ${{ secrets.GITHUB_TOKEN }}